version: '3'

services:
  planner:
    build: .
    image: fabric8-planner-runtime
    # command: npm run test:unit
    environment:
      FABRIC8_WIT_API_URL: http://localhost:8080/api/
      FABRIC8_SSO_API_URL: https://sso.prod-preview.openshift.io/
      FABRIC8_REALM: fabric8-test
    depends_on:
      - core
    networks:
      - default
    ports:
      - "8088:8080"
    volumes:
      - ./runtime/dist:/dist:Z
  core:
    image: fabric8/fabric8-wit:latest
    command: -config /usr/local/wit/etc/config.yaml
    depends_on:
      - db
    environment:
      F8_POSTGRES_HOST: db
      F8_DEVELOPER_MODE_ENABLED: 'true'
    networks:
      - default
    ports:
      - "8080:8080"
  db:
    image: registry.centos.org/postgresql/postgresql:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
    networks:
      - default