apiVersion: v1
kind: Template
metadata:
  name: f8planner
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      service: f8planner
      app: fabric8-planner
      provider: fabric8
    name: f8planner
  spec:
    replicas: 3
    selector:
      service: f8planner
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: f8planner
          app: fabric8-planner
          provider: fabric8
      spec:
        containers:
        - image: fabric8/fabric8-planner:standalone
          imagePullPolicy: Always
          name: f8planner
          ports:
          - containerPort: 80
            protocol: TCP
          env:
          - name: WS_K8S_API_SERVER
            value: ${WS_K8S_API_SERVER}
          - name: K8S_API_SERVER_PROTOCOL
            value: ${K8S_API_SERVER_PROTOCOL}
          - name: K8S_API_SERVER_BASE_PATH
            value: ${K8S_API_SERVER_BASE_PATH}
          - name: OAUTH_ISSUER
            value: ${OAUTH_ISSUER}
          - name: OAUTH_CLIENT_ID
            value: ${OAUTH_CLIENT_ID}
          - name: OAUTH_SCOPE
            value: ${OAUTH_SCOPE}
          - name: OAUTH_AUTHORIZE_URI
            value: ${OAUTH_AUTHORIZE_URI}
          - name: AUTH_LOGOUT_URI
            value: ${AUTH_LOGOUT_URI}
          - name: FABRIC8_PIPELINES_NAMESPACE
            value: ${FABRIC8_PIPELINES_NAMESPACE}
          - name: PROXIED_K8S_API_SERVER
            value: ${PROXIED_K8S_API_SERVER}
          - name: PROXY_PASS_URL
            value: ${PROXY_PASS_URL}
          - name: FABRIC8_WIT_API_URL
            value: ${FABRIC8_WIT_API_URL}
          - name: FABRIC8_RECOMMENDER_API_URL
            value: ${FABRIC8_RECOMMENDER_API_URL}
          - name: FABRIC8_FORGE_API_URL
            value: ${FABRIC8_FORGE_API_URL}
          - name: FABRIC8_SSO_API_URL
            value: ${FABRIC8_SSO_API_URL}
          - name: FABRIC8_AUTH_API_URL
            value: ${FABRIC8_AUTH_API_URL}
          - name: OPENSHIFT_CONSOLE_URL
            value: ${OPENSHIFT_CONSOLE_URL}
          - name: FABRIC8_REALM
            value: ${FABRIC8_REALM}
          - name: API_URL
            value: ${API_URL}
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 10
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: f8planner
      app: fabric8-planner
      provider: fabric8
    name: f8planner
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: f8planner
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      service: f8planner
      app: fabric8-planner
      provider: fabric8
    name: fabric8-planner
  spec:
    host: ''
    port:
      targetPort: "8080"
    to:
      kind: Service
      name: f8planner
      weight: 100
    wildcardPolicy: None
  status: {}
parameters:
- name: WS_K8S_API_SERVER
  value: api.free-int.openshift.com:443
- name: K8S_API_SERVER_PROTOCOL
  value: https
- name: K8S_API_SERVER_BASE_PATH
  value: /_p/oso
- name: OAUTH_ISSUER
  value: https://api.free-int.openshift.com:443
- name: OAUTH_CLIENT_ID
  value: fabric8
- name: OAUTH_SCOPE
  value: user:full
- name: OAUTH_AUTHORIZE_URI
  value: https://api.free-int.openshift.com:443/oauth/authorize
- name: AUTH_LOGOUT_URI
  value: https://api.free-int.openshift.com:443/connect/endsession?id_token={{id_token}}
- name: FABRIC8_PIPELINES_NAMESPACE
- name: PROXY_PASS_URL
  value: https://api.free-int.openshift.com:443
- name: OPENSHIFT_CONSOLE_URL
  value: https://console.free-int.openshift.com/console/
- name: PROXIED_K8S_API_SERVER
  value: api.free-int.openshift.com:443
- name: FABRIC8_WIT_API_URL
  value: https://api.prod-preview.openshift.io/api/
- name: FABRIC8_RECOMMENDER_API_URL
  value: https://api-bayesian.dev.rdu2c.fabric8.io/api/v1/
- name: FABRIC8_FORGE_API_URL
  value: https://forge.api.prod-preview.openshift.io
- name: FABRIC8_SSO_API_URL
  value: https://sso.prod-preview.openshift.io/
- name: FABRIC8_AUTH_API_URL
  value: https://auth.prod-preview.openshift.io/api/
- name: API_URL
  value: https://api.prod-preview.openshift.io/api/
- name: FABRIC8_REALM
  value: fabric8-test
