
kind: Template
apiVersion: v1
metadata:
  name: api
  creationTimestamp: null
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: planner
    creationTimestamp: null
    generation: 1
    labels:
      service: planner
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {  }
    triggers:
      - type: ConfigChange
    replicas: 1
    test: false
    selector:
      service: planner
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: planner
      spec:
        containers:
          - name: planner
            image: 'registry.devshift.net/almighty/almighty-ui:${IMAGE_TAG}'
            ports:
              - containerPort: 80
                protocol: TCP
            resources: {  }
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {  }
  status: {}
- kind: Service
  apiVersion: v1
  metadata:
    name: planner
    creationTimestamp: null
    labels:
      service: planner
  spec:
    ports:
      - name: '8080'
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      service: planner
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {  }
- kind: Route
  apiVersion: v1
  metadata:
    name: planner-route
    creationTimestamp: null
    labels:
      service: planner
  spec:
    host: ''
    to:
      kind: Service
      name: planner
      weight: 100
    wildcardPolicy: None
    port:
      targetPort: 8080
  status: {}
parameters:
- name: IMAGE_TAG
  value: latest